---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: ubuntu/bind9:9.16-20.04_beta
        name: {{ .Release.Name }}
        env:
{{ .Values.env | toYaml | indent 10 }}
        volumeMounts:
{{- range $file, $data := .Values.config }}
          - name: config
            mountPath: /etc/bind/{{ $file }}
            subPath: {{ $file }}
{{- end}}
        resources: {}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-configmap
